# SPDX-License-Identifier: MIT-0
---
# handlers file for minio

- name: Minio service status
  ansible.builtin.service_facts:
  listen: "Print Minio status"
- name: Print Minio status
  ansible.builtin.debug:
    msg: "Minio status for {{ inventory_hostname }}: {{ ansible_facts.services['minio.service'].state }}"
  listen: "Print Minio status"
