# SPDX-License-Identifier: MIT-0
---
# defaults file for patroni
patroni_app_cidrs: []
patroni_management_cidr: ""
patroni_inventory_group: psql
patroni_firewall_zone: patroni
patroni_firewall_ports:
  - 2379
  - 2380
  - 5432
  - 8008
patroni_pg_token: PostgreSQL_HA_Cluster
patroni_cluster_name: pg_cluster
patroni_s3_prefix: /pgbackrest
patroni_s3_bucket_name: patroni-bucket
patroni_s3_endpoint: 192.168.172.140
patroni_s3_port: 443
patroni_s3_region: eu-central-1

patroni_replicator_password: ""
patroni_postgres_password: ""
patroni_minio_key: ""
patroni_minio_secret: ""
patroni_repo_cipher_pass: ""

# CRITICAL
# Wipe etcd data dir on all nodes before start (for a failed bootstrap). Destroys DCS state!
patroni_wipe_existing_cluster: false
