patroni_data_volumes:
  - name: pgdata
    device: /dev/disk/by-id/nvme-eui.e0193c4fa4cb01ae000c29677416e545
    path: /var/lib/pgsql
    gib: 10
    owner: postgres
  - name: etcd
    device: /dev/disk/by-id/nvme-eui.7b2e376824915744000c296fc63f9c57
    path: /var/lib/etcd
    gib: 5
    owner: etcd
