patroni_create_data_volumes:
  - name: pgdata
    device: /dev/disk/by-id/nvme-eui.cf16c22054e9de9a000c29615f6b94bf
    path: /var/lib/pgsql
    gib: 10
    owner: postgres
  - name: etcd
    device: /dev/disk/by-id/nvme-eui.0117ab88611f7fa0000c296ee40558ef
    path: /var/lib/etcd
    gib: 5
    owner: etcd
