patroni_data_volumes:
  - name: pgdata
    device: /dev/disk/by-id/nvme-eui.dfda501b5e705ed2000c296807a89e53
    path: /var/lib/pgsql
    gib: 10
    owner: postgres
  - name: etcd
    device: /dev/disk/by-id/nvme-eui.465ce24032c83caf000c296c28426b54
    path: /var/lib/etcd
    gib: 5
    owner: etcd
