patroni_data_volumes:
  - name: pgdata
    device: /dev/disk/by-id/nvme-eui.679fcb31a95f73af000c296cf1d29fe4
    path: /var/lib/pgsql
    gib: 10
    owner: postgres
  - name: etcd
    device: /dev/disk/by-id/nvme-eui.03c9b493f83c9834000c2964849a42eb
    path: /var/lib/etcd
    gib: 5
    owner: etcd
