---

- name: Ensure req dirs exists and have right permissions
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: postgres
    group: postgres
    mode: '0750'
  loop:
    - /etc/pgbackrest
    - "{{ patroni_pgbackrest_data_dir }}"
    - "{{ patroni_pgbackrest_log_dir }}"

- name: Backup pgBackRest configuration
  ansible.builtin.copy:
    src: /etc/pgbackrest/pgbackrest.conf
    dest: /etc/pgbackrest/pgbackrest.conf.bak
    remote_src: true
    owner: root
    group: root
    mode: preserve
    force: false

- name: Copy pgbackrest config file
  ansible.builtin.template:
    src: pgbackrest.conf.j2
    dest: /etc/pgbackrest/pgbackrest.conf
    owner: postgres
    group: postgres
    mode: '0600'

- name: Apply pending handlers before continuing
  ansible.builtin.meta: flush_handlers

- name: Start percona-patroni
  ansible.builtin.systemd_service:
    name: percona-patroni
    state: started
    enabled: true

- name: Create stanza
  ansible.builtin.command: >-
    pgbackrest --stanza={{ patroni_cluster_name }} --no-online stanza-create
  become: true
  become_user: postgres
  run_once: true
  changed_when: false

- name: Check repo
  ansible.builtin.command: >-
    pgbackrest --stanza={{ patroni_cluster_name }} check
  become: true
  become_user: postgres
  changed_when: false
