---

- name: Ensure req dirs exists and have right permissions
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: postgres
    group: postgres
    mode: '0750'
  loop:
    - /etc/pgbackrest
    - "{{ patroni_pgbackrest_data_dir }}"
    - "{{ patroni_pgbackrest_log_dir }}"

- name: Backup pgBackRest configuration
  ansible.builtin.copy:
    src: /etc/pgbackrest/pgbackrest.conf
    dest: /etc/pgbackrest/pgbackrest.conf.bak
    remote_src: true
    owner: root
    group: root
    mode: preserve
    force: false

- name: Copy pgbackrest config file
  ansible.builtin.template:
    src: pgbackrest.conf.j2
    dest: /etc/pgbackrest/pgbackrest.conf
    owner: postgres
    group: postgres
    mode: '0600'
  no_log: true
  diff: false

- name: Creat patroni backup bin folder
  ansible.builtin.file:
    path: "/usr/local/lib/patroni"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy backup bin files
  ansible.builtin.template:
    src: "pgbackrest-bins/{{ item }}.j2"
    dest: "/usr/local/lib/patroni/{{ item }}"
    owner: root
    group: root
    mode: '0755'
  loop:
    - run-pgbackrest
    - run-dump
    - leader-gate
    - s3-client.py

- name: Load timers to systemd
  ansible.builtin.template:
    src: "systemd/{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - patroni-backup@.service
    - patroni-pgdump.service
    - patroni-pgdump.timer
    - patroni-full-backup.timer
    - patroni-incre-backup.timer
  notify: Reload systemd

- name: Apply pending handlers before continuing
  ansible.builtin.meta: flush_handlers

- name: Start percona-patroni
  ansible.builtin.systemd_service:
    name: percona-patroni
    state: started
    enabled: true

- name: Create stanza
  ansible.builtin.command: >-
    pgbackrest --stanza={{ patroni_cluster_name }} --no-online stanza-create
  become: true
  become_user: postgres
  changed_when: false

- name: Check repo
  ansible.builtin.command: >-
    pgbackrest --stanza={{ patroni_cluster_name }} check
  become: true
  become_user: postgres
  changed_when: false

- name: Dump passphrase
  ansible.builtin.copy:
    content: "{{ patroni_dump_cipher_pass }}\n"
    dest: "{{ patroni_dump_pass_file_location }}"
    owner: postgres
    group: postgres
    mode: '0600'
  no_log: true
  diff: false

- name: Enable and start the backup timers
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - patroni-full-backup.timer
    - patroni-incre-backup.timer
    - patroni-pgdump.timer
