# SPDX-License-Identifier: MIT-0
---
# tasks file for patroni
- name: Prepare system
  ansible.builtin.include_tasks: prepare_hosts.yml

- name: Configure Etcd
  ansible.builtin.include_tasks: etcd.yml

- name: Configure Patroni cluster
  ansible.builtin.include_tasks: patroni.yml

- name: Configure pgBackRest
  ansible.builtin.include_tasks: backup.yml

- name: Check cluster status
  ansible.builtin.include_tasks: check_status.yml
