---

- name: Verify required passwords are provided
  ansible.builtin.assert:
    that:
      - patroni_postgres_password | default('') | length > 0
      - patroni_replicator_password | default('') | length > 0
      - patroni_repo_cipher_pass | default('') | length > 0
      - patroni_dump_cipher_pass | default('') | length > 0
      - patroni_minio_key | default('') | length > 0
      - patroni_minio_secret | default('') | length > 0
    fail_msg: >-
      Please set patroni_postgres_password and patroni_replicator_password.
    success_msg: "Passwords have been set."

- name: Verify supported operating system
  ansible.builtin.assert:
    that:
      - ansible_facts['distribution'] == 'Rocky'
      - ansible_facts['distribution_major_version'] == '9'
      - ansible_facts['service_mgr'] == 'systemd'
    fail_msg: >-
      Unsupported system.
      This role requires Rocky Linux 9 with systemd.
    success_msg: "Supported system: Rocky Linux 9 with systemd."

- name: Verify data volume definitions
  ansible.builtin.assert:
    that:
      - item.name | default('', true) | length > 0
      - item.device | default('', true) | length > 0
      - item.path | default('', true) | length > 0
      - item.gib | int > 0
      - item.owner | default('', true) | length > 0
    fail_msg: "Invalid data volume definition: {{ item }}"
  loop: "{{ patroni_data_volumes }}"
  loop_control:
    label: "{{ item.name | default('<unnamed>', true) }}"
