# SPDX-License-Identifier: MIT-0
---
# handlers file for patroni
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: udev reload
  ansible.builtin.command: udevadm control --reload-rules

- name: Patroni service status
  ansible.builtin.service_facts:
  listen: "Patroni status"
- name: Print Patroni status
  ansible.builtin.debug:
    msg: "Patroni status for {{ inventory_hostname }}: {{ ansible_facts.services['percona-patroni.service'].state }}"
  listen: "Patroni status"

- name: Etcd service status
  ansible.builtin.service_facts:
  listen: "Etcd status"
- name: Print etcd status
  ansible.builtin.debug:
    msg: "Etcd status for {{ inventory_hostname }}: {{ ansible_facts.services['etcd.service'].state }}"
  listen: "Etcd status"

- name: Check etcd cluster health
  ansible.builtin.command: |
    etcdctl \
      --endpoints=https://127.0.0.1:2379 \
      --cacert={{ patroni_etcd_ssl }}/ca.crt \
      --cert={{ patroni_etcd_ssl }}/etcd-{{ inventory_hostname }}.crt \
      --key={{ patroni_etcd_ssl }}/etcd-{{ inventory_hostname }}.key \
      endpoint health \
      --cluster
  register: patroni_etcd_health
  until: patroni_etcd_health.rc == 0
  retries: 12
  delay: 5
  changed_when: false
  run_once: true