---

- name: Verify required passwords are provided
  ansible.builtin.assert:
    that:
      - minio_admin_username | default('') | length > 0
      - minio_admin_password | default('') | length > 0
    fail_msg: >-
      Please set required variables.
    success_msg: "Required variables have been set."

- name: Verify supported operating system
  ansible.builtin.assert:
    that:
      - ansible_facts['distribution'] == 'Rocky'
      - ansible_facts['distribution_major_version'] == '9'
      - ansible_facts['service_mgr'] == 'systemd'
    fail_msg: >-
      Unsupported system.
      This role requires Rocky Linux 9 with systemd.
    success_msg: "Supported system: Rocky Linux 9 with systemd."
